### ISSUE TITLE
gist won't update after July 31, 2020

### ISSUE THREAD

**Issue by meek2100** [majkinetor/au-packages-template#19]
I have the gistid defined in the appveyor.xml file, but since July 31st, it just fails with the following message.

Now it just says: 

Running Gist
  ERROR:  
    {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/gists#update-a-gist"}

**Comment by majkinetor** [comment]
Since your gist https://gist.github.com/meek2100/d1727a692d06b4b337db230100c9c2f8 exists , its probably something related to GH auth or token.

AU definitely works as can be easily seen on number of other repositories.

**Comment by meek2100** [comment]
Thanks for looking into this.  I'll keep exploring additional items on my side.  Just seems odd it randomly stopped.
