### ISSUE TITLE
Disable timestamp while updating package

### ISSUE THREAD

**Issue by kamack38** [majkinetor/au-packages-template#29]
Can I disable adding to version timestamp while maintaining updating versions?
**How it works now :**
```
package is updated to 2.10.2.20211015
```

**How I'd like it to work :**
```
package is updated to 2.10.2
```

**Comment by majkinetor** [comment]
It happens only if you force update. So don't do it. 

You could also use `$au_Version` variable - so called explicit version.

**Comment by kamack38** [comment]
How can I delete `.nupkg`'s for previous versions?

**Comment by kamack38** [comment]
Ok, I resolved this issue by setting `Force = $false` and adding this to my `update_all.ps1` script : 
```
AfterEach = {
    $nupkg = Get-ChildItem -Exclude 'nupkgs' | Get-ChildItem -Recurse | Where-Object Name -Match .*.nupkg
    if ($nupkg -ne $null) {
        $pkgName = ($nupkg.Name -split ".\d+")[0]
        Remove-Item "..\nupkgs\$pkgName.*"
        Get-ChildItem -Depth 1 | Where-Object Name -Match .*.nupkg | Move-Item -Destination ..\nupkgs\ -Force
    }
}
```
