### ISSUE TITLE
Migrate to Visual Studio * image in appveyor.yml

### ISSUE THREAD

**Issue by galeksandrp** [majkinetor/au-packages-template#7]
According to
- https://www.appveyor.com/docs/build-environment/#hyper-v
- https://www.appveyor.com/docs/build-environment/#build-worker-images

only `Visual Studio *` images are pre-heated, and therefore does not have ~3min delay before build start.

Although using `Visual Studio 2013`/`Visual Studio 2015` is not succesful (may be due to old powershell), is there any issues preventing migration to `Visual Studio 2017` image?

**Comment by majkinetor** [comment]
Not that I know any.

@AdmiringWorm maybe has experience with this.

**Comment by majkinetor** [comment]
You can try it on your own repo and tell the news here TBH.

**Comment by AdmiringWorm** [comment]
yes, the build time itself is increased when using the Visual Studio 2017 image.
I've tried that in the past on this repo, and it always reach the maximum time for appveyor builds.
